kind: pipeline
type: docker
name: pulp-ui

# keep Drone from doing the default HTTPS clone (self-signed cert issues)
clone:
  disable: true

steps:
  # --- clone from Gitea over SSH:2222 using host-mounted key (same style as WikiJS) ---
  - name: clone-pulp-ui
    image: alpine:3.20
    volumes:
      - name: ssh
        path: /root/.ssh
    commands:
      - apk add --no-cache git openssh
      - mkdir -p /drone/src
      - cd /drone/src
      - git config --global --add safe.directory /drone/src
      - |
        GIT_SSH_COMMAND="ssh -i /root/.ssh/id_ed25519 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p 2222" \
          git clone git@172.16.111.190:cyber-sbs/pulp-ui.git .

  - name: debug-dir
    image: alpine:3.20
    commands:
      - ls -alhR /drone/src | head -200

  # --- restore cache (node_modules) ---
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - /drone/src/node_modules
        - /root/.npm

  # --- deps / build with Node 22 (pulp-ui requires >=20) ---
  - name: deps-and-build
    image: node:22-bookworm-slim   # ← not alpine
    volumes:
      - name: cache
        path: /cache
    environment:
      # keep npm quieter & faster in CI
      PULP_UI_COMMIT: ${DRONE_COMMIT_SHA} 
      npm_config_audit: "false"
      npm_config_fund: "false"
      npm_config_update_notifier: "false"
      npm_config_loglevel: "info"
    commands:
      - node -v && npm -v
      # upgrade npm (works around the bug on 10.9.3)
      - npm i -g npm@latest
      - npm -v
      - npm ci --no-audit --no-fund --legacy-peer-deps
      - cd /drone/src
      - |
        if [ ! -f package-lock.json ]; then
          echo "⚠️  package-lock.json missing; falling back to 'npm install'"
          npm install --legacy-peer-deps || (cat /root/.npm/_logs/*-debug-0.log || true; exit 1)
        else
          npm ci --legacy-peer-deps || (cat /root/.npm/_logs/*-debug-0.log || true; exit 1)
        fi
      - npm run build

  # --- rebuild cache after deps ---
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /drone/src/node_modules
         - /root/.npm

  - name: docker_login_check
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - test -n "$DOCKER_USERNAME" || (echo "DOCKER_USERNAME missing" && exit 1)
      - test -n "$DOCKER_PASSWORD" || (echo "DOCKER_PASSWORD missing" && exit 1)
      - echo "$DOCKER_PASSWORD" | docker login 172.16.111.190 -u "$DOCKER_USERNAME" --password-stdin


  # --- Docker image publish: short SHA tag ---
  - name: docker_publish_sha
    image: plugins/docker:20
    settings:
      registry: 172.16.111.190
      repo: 172.16.111.190/cyber-sbs/pulp-ui
      insecure: true
      tags:
        - latest
        - "${DRONE_COMMIT_SHA:0:7}"
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

      dockerfile: Dockerfile
      context: /drone/src
      build_args:
        - VERSION=${DRONE_TAG:-${DRONE_COMMIT_SHA:0:7}}
        - COMMIT=${DRONE_COMMIT_SHA}
        - BUILD_DATE=${DRONE_BUILD_CREATED}
    when:
      event:
        - push
        - tag

  # --- Docker image publish: 'latest' on main/master ---
  - name: docker_publish_latest
    image: plugins/docker:20
    settings:
      registry: 172.16.111.190
      repo: 172.16.111.190/cyber-sbs/pulp-ui
      insecure: true
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
        
      dockerfile: Dockerfile
      context: /drone/src
      build_args:
        - VERSION=${DRONE_TAG:-${DRONE_COMMIT_SHA:0:7}}
        - COMMIT=${DRONE_COMMIT_SHA}
        - BUILD_DATE=${DRONE_BUILD_CREATED}
    when:
      branch:
        - main
        - master
      event:
        - push

volumes:
  # same pattern as your working WikiJS pipeline
  - name: ssh
    host:
      path: /home/cyberdev/gitea-stack/.ssh   # must contain id_ed25519 with read access in Gitea

  - name: cache
    host:
      path: /home/cyberdev/.drone-cache

trigger:
  branch:
    - main
    - master
    - develop
  event:
    - push
    - pull_request
    - tag
