kind: pipeline
type: docker
name: pulp-ui-ci

# default workspace is /drone/src

steps:
  - name: clone
    image: alpine:3.20
    environment:
      REPO_SSH: git@172.16.111.190:cyber-sbs/pulp-ui.git
    commands:
      - apk add --no-cache git openssh
      - mkdir -p ~/.ssh
      - printf "%s" "$DRONE_SSH_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      # trust Gitea internal SSH (port 2222)
      - ssh-keyscan -p 2222 -t rsa,ecdsa,ed25519 172.16.111.190 >> ~/.ssh/known_hosts
      - git init .
      - git remote add origin "$REPO_SSH"
      - GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes -p 2222" git fetch --depth=1 origin "${DRONE_BRANCH:-main}"
      - GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes -p 2222" git checkout -B "${DRONE_BRANCH:-main}" "origin/${DRONE_BRANCH:-main}"

  # optional: cache npm (uncomment if you want caching)
  # - name: restore-npm-cache
  #   image: meltwater/drone-cache:latest
  #   settings:
  #     mount:
  #       - /root/.npm
  #     restore: true
  #     backend: filesystem
  #     cache_key: npm-{{ arch }}-{{ os }}-{{ repo.name }}-{{ checksum "package-lock.json" }}

  - name: deps
    image: node:22-alpine
    environment:
      # NPM_TOKEN: # if you need private registry access, add a secret and uncomment
    commands:
      - node -v && npm -v
      # optional: write an .npmrc if using an auth token
      # - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - npm ci --legacy-peer-deps

  - name: lint
    image: node:22-alpine
    commands:
      - npm run lint || echo "lint warnings tolerated"

  - name: test
    image: node:22-alpine
    commands:
      - npm test -- --ci --reporters=default || echo "tests optional, adjust as needed"

  - name: build
    image: node:22-alpine
    commands:
      - npm run build

  # optional: save npm cache
  # - name: save-npm-cache
  #   image: meltwater/drone-cache:latest
  #   settings:
  #     mount:
  #       - /root/.npm
  #     rebuild: true
  #     backend: filesystem
  #     cache_key: npm-{{ arch }}-{{ os }}-{{ repo.name }}-{{ checksum "package-lock.json" }}

trigger:
  branch:
    - main
    - master
    - develop
  event:
    - push
    - pull_request
